#!/bin/sh
set -e
# Automatically added by dh_icons/12.10ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if which update-icon-caches >/dev/null 2>&1 ; then
		update-icon-caches /usr/share/icons/ukui-icon-theme-default /usr/share/icons/ukui-icon-theme-unity
	fi
fi
# End automatically added section
